name: flickr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  photo_view:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  transparent_image: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.4.0
  timeago: ^3.0.2
  share_plus: ^2.1.2
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  responsive_widgets: ^2.0.1
  firebase_auth: ^1.3.0
  cloud_firestore: ^2.0.0
  provider: ^5.0.0
  mockito: ^5.0.7
  camera: ^0.8.1
  image_picker: ^0.7.4
  google_maps_webservice: ^0.0.19
  multi_image_picker: ^4.8.0
  holding_gesture: ^1.1.0
  video_player: ^2.1.1
  video_thumbnail: ^0.3.3
  flutter_svg: ^0.20.0-nullsafety.3
  google_fonts: ^2.1.0
  dartdoc: ^0.44.0
  flutter_signin_button: ^2.0.0
  jwt_decode: ^0.3.1
  google_sign_in: ^5.0.4
  firebase_core: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  dio:  ^4.0.0
  fluttertoast: ^8.0.7



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/columnone.jpg
    - lib/assets/columntwo.jpg
    - lib/assets/columnthree.jpg
    - lib/assets/columnfour.jpg
    - lib/assets/flickr.png
    - lib/assets/my_profile.jpg
    - lib/assets/their_profile.jpeg
    - lib/assets/photo_1.jpeg
    - lib/assets/follower2.jpg
    - lib/assets/background.jpg
    - lib/assets/follower3.jpeg
    - lib/assets/post2.jpg
    - lib/assets/photo4.jpg
    - lib/assets/photo5.jpg
    - lib/assets/profile3.png
    - lib/assets/profile4.png
    - lib/assets/profile6.jpg
    - lib/assets/flickr1.png
    - lib/assets/istanbul.jpg
    - lib/assets/toothpaste.jpeg
    - lib/assets/perfume1.jpeg
    - lib/assets/perfume2.jpeg
    - lib/assets/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FreeSet
      fonts:
        - asset: fonts/FreeSet-Bold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
